project:
  type: website
  output-dir: docs

website:
  title: "Layton R blog"
  site-url: https://graphdr.github.io/data-stories
  repo-url: https://github.com/graphdr/data-stories
  repo-actions: [issue]
  description: "A blog about visual rhetoric, chart design, and R."
  favicon: images/favicon.png
  reader-mode: true

  sidebar:
    style: "floating"
    search: false
    contents:
      - section: "r-bloggers"
        url: https://r-bloggers.com
      - section: "stackoverflow"
        url: https://stackoverflow.com/questions/tagged/r
      - section: "data.table"
        url: https://rdatatable.gitlab.io/data.table/
      - section: "happy git"
        url: https://happygitwithr.com/
 
  navbar:
   right:
    - text: "License"
      href: license.html 
    - text: "About"
      href: about.qmd
    - icon: envelope-fill
      href: mailto:graphdoctor@gmail.com
    - icon: git
      href: https://github.com/graphdr/data-stories
    - icon: rss
      href: index.xml     
       
  margin-header: redirect.html
  
  page-footer:
    center: 
      - text: "Copyright 2022 Richard A. Layton"
        
format:
  html:
    theme: flatly
    css: styles.css
    code-fold: true
    code-summary: "R code"
    code-overflow: wrap
    code-copy: true

comments:
  utterances:
    repo: graphdr/data-stories


