project:
  type: website
  output-dir: docs

website:
  title: "Layton R blog"
  site-url: https://graphdr.github.io/data-stories
  repo-url: https://github.com/graphdr/data-stories
  description: "A blog about visual rhetoric, chart design, and R."
  favicon: images/favicon.png
  opengraph: true
  
  sidebar: 
    title: Links
    style: docked
  
  navbar:
   right:
    - text: "Home"
      href: index.qmd
    - text: "License"
      href: license.html 
    - text: "About"
      href: about.qmd
    - icon: github
      href: https://github.com/graphdr/data-stories
    - icon: rss
      href: index.xml     
        
format:
  html:
    theme: flatly
    css: styles.css
    code-fold: true
    code-summary: "R code"



